# config.yml
train:
  n_epoch: 1000
  lr_init: 1.0e-3
  lr_end: 1.0e-6
  clip: 1.0
  wdecay: 1.0e-5
  batch_size: 1024
  n_steps_epoch: 1
    
model:
  ndim: 3
  cdim: 5
  edim: 64
  layers: 2
  width: 256
  w_embed: 32
  n_heads: 4
  dropout: 0.0
  vae: False
  sigma: 1.0e-3

paths:
  data: "./data/data.h5"
  model_1: "./models/mogp_model_state_psNG.pth"
  likelihood_1: "./models/mogp_likelihood_state_psNG.pth"
  model_2: "./models/mogp_model_state_spNG.pth"
  likelihood_2: "./models/mogp_likelihood_state_spNG.pth"
  output_dir: "./results/"

evaluation:
  n_eval_samples: 512
  n_traj_pts: 100
  evalindices: [4027, 131, 437]
  trace_method: "autograd"